export const GEOLOCATING = 'GEOLOCATING';
export const UPDATE_CURRENT_LOCATION = 'UPDATE_CURRENT_LOCATION';
export const ADD_DESTINATION = 'ADD_DESTINATION';
export const ADD_JOURNEYS = 'ADD_JOURNEYS';
export const REMOVE_JOURNEYS = 'REMOVE_JOURNEYS';
export const REMOVE_DESTINATION = 'REMOVE_DESTINATION';
